apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-deployment
  template:
    metadata:
      labels:
        app: python-deployment
    spec:
      containers:
      - name: python-deployment
        image: registry.digitalocean.com/testregistry/digitaloceanflaskk8s:latest
        ports:
        - containerPort: 8080